// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYmCVlBFhdU0UhOIU8F1EQ5rdJjl8ppog',
    appId: '1:902069235624:web:1e3a69ce7cab4dec8af79d',
    messagingSenderId: '902069235624',
    projectId: 'ozone-a25d3',
    authDomain: 'ozone-a25d3.firebaseapp.com',
    databaseURL: 'https://ozone-a25d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ozone-a25d3.firebasestorage.app',
    measurementId: 'G-EQYMQY64CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHYe8Amlb6rrvmn1Bw4zeO7AaNEdOGFM',
    appId: '1:902069235624:android:759d983c0666f0b88af79d',
    messagingSenderId: '902069235624',
    projectId: 'ozone-a25d3',
    databaseURL: 'https://ozone-a25d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ozone-a25d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqrr-zyv4-HG5rlylLOYBvaQtSAaTHPXg',
    appId: '1:902069235624:ios:1864bd576010c1138af79d',
    messagingSenderId: '902069235624',
    projectId: 'ozone-a25d3',
    databaseURL: 'https://ozone-a25d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ozone-a25d3.firebasestorage.app',
    iosClientId: '902069235624-9rg7enatg2m2570vp2qnolm3nu55skpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ojonisasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqrr-zyv4-HG5rlylLOYBvaQtSAaTHPXg',
    appId: '1:902069235624:ios:1864bd576010c1138af79d',
    messagingSenderId: '902069235624',
    projectId: 'ozone-a25d3',
    databaseURL: 'https://ozone-a25d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ozone-a25d3.firebasestorage.app',
    iosClientId: '902069235624-9rg7enatg2m2570vp2qnolm3nu55skpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ojonisasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYmCVlBFhdU0UhOIU8F1EQ5rdJjl8ppog',
    appId: '1:902069235624:web:d4badb7e0a367e268af79d',
    messagingSenderId: '902069235624',
    projectId: 'ozone-a25d3',
    authDomain: 'ozone-a25d3.firebaseapp.com',
    databaseURL: 'https://ozone-a25d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ozone-a25d3.firebasestorage.app',
    measurementId: 'G-E62F9ZRT14',
  );
}
